### ISSUE TITLE
Update translation to Django 4

### ISSUE THREAD

**Issue by src-r-r** [furious-luke/django-address#161]
```
Traceback (most recent call last):
  File "./manage.py", line 31, in <module>
    execute_from_command_line(sys.argv)
  File "~/project/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 425, in execute_from_command_line
    utility.execute()
  File "~/project/.venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute
    django.setup()
  File "~/project/.venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "~/project/.venv/lib/python3.8/site-packages/django/apps/registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "~/project/.venv/lib/python3.8/site-packages/django/apps/config.py", line 123, in create
    mod = import_module(mod_path)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "~/project/.venv/lib/python3.8/site-packages/django_address/apps.py", line 2, in <module>
    from django.utils.translation import ugettext_lazy as _
ImportError: cannot import name 'ugettext_lazy' from 'django.utils.translation' (~/project/.venv/lib/python3.8/site-packages/django/utils/translation/__init__.py)
```

Django has been warning about this deprecation for a while.

It's obviously a simple fix--I'll even get one out this morning since it's a showstopper (for me).

**Comment by src-r-r** [comment]
This already appears to be fixed in the latest repo.
