### ISSUE TITLE
Issue with Django 1.9

### ISSUE THREAD

**Issue by mattijevi** [furious-luke/django-address#25]
I am trying out django 1.9 and getting this:

Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "lib/python2.7/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "lib/python2.7/site-packages/django/core/management/__init__.py", line 324, in execute
    django.setup()
  File "lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "lib/python2.7/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "lib/python2.7/site-packages/django/apps/config.py", line 202, in import_models
    self.models_module = import_module(models_module_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/mattmatijevich/Documents/next-door-now/trunk/ndn/website/models.py", line 14, in <module>
    from address.models import AddressField
  File "lib/python2.7/site-packages/address/models.py", line 3, in <module>
    from django.db.models.fields.related import ForeignObject, ReverseSingleRelatedObjectDescriptor
ImportError: cannot import name ReverseSingleRelatedObjectDescriptor

**Comment by furious-luke** [comment]
Hi there!
Yep, it looks like 1.9 has moved and renamed that symbol. I'll see about updating django-address asap.
Cheers,
Luke

**Comment by erbridge** [comment]
This is fixed by #28.

**Comment by jgeerds** [comment]
This issue is already fixed so we could close it
