### ISSUE TITLE
Does django-address works with Django 3.0.2?

### ISSUE THREAD

**Issue by peiliu** [furious-luke/django-address#91]
Does django-address works with Django 3?  I getting the following error when makemigration:
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\pei_l\Documents\Projects\django\wmtennis\env\lib\site-packages\django\core\management\__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "C:\Users\pei_l\Documents\Projects\django\wmtennis\env\lib\site-packages\django\core\management\__init__.py", line 377, in execute
    django.setup()
  File "C:\Users\pei_l\Documents\Projects\django\wmtennis\env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\pei_l\Documents\Projects\django\wmtennis\env\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\pei_l\Documents\Projects\django\wmtennis\env\lib\site-packages\django\apps\config.py", line 211, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\pei_l\AppData\Local\Programs\Python\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\pei_l\Documents\Projects\django\wmtennis\env\lib\site-packages\address\models.py", line 7, in <module>
    from django.utils.encoding import python_2_unicode_compatible
ImportError: cannot import name 'python_2_unicode_compatible' from 'django.utils.encoding'

**Comment by SoldierGamma** [comment]
I am waiting on this, it would be a great help.

**Comment by banagale** [comment]
@peiliu, @EnricoGallus, @SoldierGamma:

The current release does not support Django 3.0.

Python 2 APIs [were removed](https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis) in Django 3.0. That's why there's an error here.

We currently have [a PR](https://github.com/furious-luke/django-address/pull/96) that is working up through Django 3.0.5. If you're able to clone that PR, you can use the package now.

We're [working to triage](https://github.com/furious-luke/django-address/issues/98) tickets and PRs, and hope for an update that will include Django 3.0 support soon. Please follow #98 for updates on availability of D3.0+ support.
